source "https://rubygems.org"

gem 'sqlite3', :platforms => [:ruby]
gem 'activerecord-jdbcsqlite3-adapter', :platforms => [:jruby]

platforms :rbx do
  gem 'rubysl', '~> 2.0'
  gem 'rubinius-developer_tools'
  gem 'rubysl-test-unit'
end


gem 'activerecord', '>= 4.0.0', '< 5'

# Specify your gem's dependencies in acts_as_list.gemspec
gemspec :path => File.join('..', '..')

gem 'rake'
